### ISSUE TITLE
Linux Config File Issue

### ISSUE THREAD

**Issue by wkonix** [Powerthegreat/EditMobDrops#2]
When I installed this mod on my Forge server running on CentOS7, it generated a file called exactly "config\editmobdrops\editmobdrops.cfg" in the root directory of the server installation instead of in the config folder. 

![issue](https://user-images.githubusercontent.com/63530165/80904428-4c59ce80-8cd8-11ea-8b19-a0260f1fecf0.png)

It works fine otherwise, but it is an issue none-the-less, and I figured I should mention it.

**Comment by Powerthegreat** [comment]
Seems like this is because of the difference between the way linux and windows handle file systems, I'll look into it.

**Comment by Powerthegreat** [comment]
Next update should fix this issue, once the update releases, just move that config file to the correct location.

**Comment by wkonix** [comment]
That was surprisingly quick. Thanks for the fix!
